# Business Intelligence Lab Submission Markdown

<Data Pink Panthers> \<26/09/23\>

-   [Student Details](#student-details)
-   [Setup Chunk](#setup-chunk)
-   [Loading the Student Performance Dataset](#loading-the-student-performance-dataset)
    -   [Description of the Dataset](#description-of-the-dataset)
-   [\<You can Provide Another Appropriate Title Here if you wish\>](#you-can-provide-another-appropriate-title-here-if-you-wish)
    -   [\<You Can Have a Sub-Title Here if you wish\>](#you-can-have-a-sub-title-here-if-you-wish)
    -   [\<You Can Have Another Sub-Title Here if you wish\>](#you-can-have-another-sub-title-here-if-you-wish)

# Student Details {#student-details}

+---------------------------------------------------+---------------------------------------------+--------------------+
| **Student ID Numbers and Names of Group Members** | \| 1. 137315 - C - Yashvi Bhadania          |                    |
|                                                   |                                             |                    |
|                                                   | \| 2. 134668 - C - June Ndinda Mutiso       |                    |
|                                                   |                                             |                    |
|                                                   | \| 3. 135227 - C - Innocent Mbuvi           |                    |
|                                                   |                                             |                    |
|                                                   | \| 4. 134253 - C - Uzair Farooq             |                    |
|                                                   |                                             |                    |
|                                                   | \| 5. 135109 - C - Jackson Kaburu           |                    |
+---------------------------------------------------+---------------------------------------------+--------------------+
|                                                   | **GitHub Classroom Group Name**             | Data Pink Panthers |
+---------------------------------------------------+---------------------------------------------+--------------------+
| **Course Code**                                   | BBT4206                                     |                    |
+---------------------------------------------------+---------------------------------------------+--------------------+
| **Course Name**                                   | Business Intelligence II                    |                    |
+---------------------------------------------------+---------------------------------------------+--------------------+
| **Program**                                       | Bachelor of Business Information Technology |                    |
+---------------------------------------------------+---------------------------------------------+--------------------+
| **Semester Duration**                             | 21^st^ August 2023 to 28^th^ November 2023  |                    |
+---------------------------------------------------+---------------------------------------------+--------------------+

# Step 1: Setup Chunk {#setup-chunk}

We start by installing all the required packages

``` r
###STEP ONE:###
# Install renv:
if (!is.element("renv", installed.packages()[, 1])) {
  install.packages("renv", dependencies = TRUE)
}
require("renv")


.libPaths()


# Command to see which packages are available in
# each library:
lapply(.libPaths(), list.files)

# Execute the following code to reinstall the specific package versions
# recorded in the lockfile:
renv::restore()

# One of the packages required to use R in VS Code is the "languageserver"
# package. It can be installed manually as follows if you are not using the
# renv::restore() command.
if (!is.element("languageserver", installed.packages()[, 1])) {
  install.packages("languageserver", dependencies = TRUE)
}
require("languageserver")
```

------------------------------------------------------------------------

**Note:** the following "*KnitR*" options have been set as the defaults in this markdown:\
`knitr::opts_chunk$set(echo = TRUE, warning = FALSE, eval = TRUE, collapse = FALSE, tidy.opts = list(width.cutoff = 80), tidy = TRUE)`.

More KnitR options are documented here <https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html> and here <https://yihui.org/knitr/options/>.

``` r
knitr::opts_chunk$set(
    eval = TRUE,
    echo = TRUE,
    warning = FALSE,
    collapse = FALSE,
    tidy = TRUE
)
```

------------------------------------------------------------------------

**Note:** the following "*R Markdown*" options have been set as the defaults in this markdown:

> output:
>
> github_document:\
> toc: yes\
> toc_depth: 4\
> fig_width: 6\
> fig_height: 4\
> df_print: default
>
> editor_options:\
> chunk_output_type: console

# STEP 2,3 Loading the Student Performance Dataset {#loading-the-student-performance-dataset}

The 20230412-20230719-BI1-BBIT4-1-StudentPerformanceDataset is then loaded. The dataset and its metadata are available here: <https://drive.google.com/drive/folders/1-BGEhfOwquXF6KKXwcvrx7WuZXuqmW9q?usp=sharing>

``` r
student_performance_dataset <-
  readr::read_csv(
                  "../data/20230412-20230719-BI1-BBIT4-1-StudentPerformanceDataset.CSV", # nolint
                  col_types =
                  readr::cols(
                              class_group =
                              readr::col_factor(levels = c("A", "B", "C")),
                              gender = readr::col_factor(levels = c("1", "0")),
                              YOB = readr::col_date(format = "%Y"),
                              regret_choosing_bi =
                              readr::col_factor(levels = c("1", "0")),
                              drop_bi_now =
                              readr::col_factor(levels = c("1", "0")),
                              motivator =
                              readr::col_factor(levels = c("1", "0")),
                              read_content_before_lecture =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              anticipate_test_questions =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              answer_rhetorical_questions =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              find_terms_I_do_not_know =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              copy_new_terms_in_reading_notebook =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              take_quizzes_and_use_results =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              reorganise_course_outline =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              write_down_important_points =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              space_out_revision =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              studying_in_study_group =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              schedule_appointments =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              goal_oriented =
                              readr::col_factor(levels =
                                                c("1", "0")),
                              spaced_repetition =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4")),
                              testing_and_active_recall =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4")),
                              interleaving =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4")),
                              categorizing =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4")),
                              retrospective_timetable =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4")),
                              cornell_notes =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4")),
                              sq3r = readr::col_factor(levels =
                                                       c("1", "2", "3", "4")),
                              commute = readr::col_factor(levels =
                                                          c("1", "2",
                                                            "3", "4")),
                              study_time = readr::col_factor(levels =
                                                             c("1", "2",
                                                               "3", "4")),
                              repeats_since_Y1 = readr::col_integer(),
                              paid_tuition = readr::col_factor(levels =
                                                               c("0", "1")),
                              free_tuition = readr::col_factor(levels =
                                                               c("0", "1")),
                              extra_curricular = readr::col_factor(levels =
                                                                   c("0", "1")),
                              sports_extra_curricular =
                              readr::col_factor(levels = c("0", "1")),
                              exercise_per_week = readr::col_factor(levels =
                                                                    c("0", "1",
                                                                      "2",
                                                                      "3")),
                              meditate = readr::col_factor(levels =
                                                           c("0", "1",
                                                             "2", "3")),
                              pray = readr::col_factor(levels =
                                                       c("0", "1",
                                                         "2", "3")),
                              internet = readr::col_factor(levels =
                                                           c("0", "1")),
                              laptop = readr::col_factor(levels = c("0", "1")),
                              family_relationships =
                              readr::col_factor(levels =
                                                c("1", "2", "3", "4", "5")),
                              friendships = readr::col_factor(levels =
                                                              c("1", "2", "3",
                                                                "4", "5")),
                              romantic_relationships =
                              readr::col_factor(levels =
                                                c("0", "1", "2", "3", "4")),
                              spiritual_wellnes =
                              readr::col_factor(levels = c("1", "2", "3",
                                                           "4", "5")),
                              financial_wellness =
                              readr::col_factor(levels = c("1", "2", "3",
                                                           "4", "5")),
                              health = readr::col_factor(levels = c("1", "2",
                                                                    "3", "4",
                                                                    "5")),
                              day_out = readr::col_factor(levels = c("0", "1",
                                                                     "2", "3")),
                              night_out = readr::col_factor(levels = c("0",
                                                                       "1", "2",
                                                                       "3")),
                              alcohol_or_narcotics =
                              readr::col_factor(levels = c("0", "1", "2", "3")),
                              mentor = readr::col_factor(levels = c("0", "1")),
                              mentor_meetings = readr::col_factor(levels =
                                                                  c("0", "1",
                                                                    "2", "3")),
                              `Attendance Waiver Granted: 1 = Yes, 0 = No` =
                              readr::col_factor(levels = c("0", "1")),
                              GRADE = readr::col_factor(levels =
                                                        c("A", "B", "C", "D",
                                                          "E"))),
                  locale = readr::locale())
```

## STEP 4,5 Description of the Dataset {#description-of-the-dataset}

We then display the number of observations and number of variables. We have 101 observations and 100 variables to work with.

``` r
dim(student_data)
```

```         
## [1] 101 100
```

Next, we display the quartiles for each numeric variable[*... think of this process as **"storytelling using the data."** Tell us what is happening; tell us what you are discovering as you proceed with the markdown; walk us through your code step-by-step (a code walkthrough).*]{#highlight style="color: blue"}

``` r
summary(student_performance_dataset)
```

```         
## STEP FOUR & FIVE: PREVIEWING THE DATASET
# Dimensions refer to the number of observations (rows) and the number of
# attributes/variables/features (columns). Execute the following commands to
# display the dimensions of your datasets:

dim(student_data)
student_data_clean <- student_data                                   # Duplicate data frame
student_data_clean[student_data_clean == "" | student_data_clean == " "] <- NA  # Replace blank & space by NA
student_data_clean      
View(student_data_clean)
View(student_data)
```

## STEP 6 Description of the Dataset

``` r
#STEP 6:IDENTIFYING THE DATA TYPES
sapply(student_data, class)
```

## STEP 7 Description of the Dataset

``` r
#STEP 7:Identify the number of instances that belong to each class.
student_data_freq <- student_data$class_group
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$gender
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$YOB
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$regret_choosing_bi
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$drop_bi_now
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$motivator
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$read_content_before_lecture
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$anticipate_test_questions
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$answer_rhetorical_questions
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$find_terms_I_do_not_know
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$copy_new_terms_in_reading_notebook
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$take_quizzes_and_use_results
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$reorganise_course_outline
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$write_down_important_points
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$space_out_revision
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$studying_in_study_group
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$schedule_appointments
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$goal_oriented
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$spaced_repetition
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$testing_and_active_recall
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$interleaving
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$categorizing
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$retrospective_timetable
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$cornell_notes
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$sq3r
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$commute
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$study_time
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$repeats_since_Y1
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$paid_tuition
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$free_tuition
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$extra_curricular
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$sports_extra_curricular
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$exercise_per_week
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$meditate
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$pray
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$internet
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$laptop
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$family_relationships
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$friendships
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$romantic_relationships
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$spiritual_wellnes
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$financial_wellness
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$health
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$day_out
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$night_out
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$alcohol_or_narcotics
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$mentor
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)

student_data_freq <- student_data$mentor_meetings
cbind(frequency = table(student_data_freq),
      percentage = prop.table(table(student_data_freq)) * 100)
```

# Measuring the Distribution of the Data {#you-can-provide-another-appropriate-title-here-if-you-wish}

## STEP 8 Calculating the Mode {#you-can-have-a-sub-title-here-if-you-wish}

``` r
#STEP 8: Calculate the mode
student_data_classgroup_mode <- names(table(student_data$class_group))[
  which(table(student_data$class_group) == max(table(student_data$class_group)))
]
print(student_data_classgroup_mode)
```

## STEP 9 Measure the distribution of the data

``` r
### STEP 9. Measure the distribution of the data for each variable ----
summary(student_data)
summary(student_dataset)
```

## STEP 10 Measuring the Standard Deviation

``` r
### STEP 10. Measure the standard deviation of each variable ----
sapply(student_dataset[, c( 75, 76, 77, 78, 79, 80, 
                          81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 
                          91, 92, 93, 94, 95, 96, 97, 98, 99)], sd)
```

## STEP 11 Measuring Variance of each variable

``` r
### STEP 11. Measure the variance of each variable ----

sapply(student_dataset[, c( 75, 76, 77, 78, 79, 80, 
                               81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 
                               91, 92, 93, 94, 95, 96, 97, 98, 99)], var)
```

## STEP 12 Measuring Kurtosis of each variable

``` r
### STEP 12. Measure the kurtosis of each variable ----
if (!is.element("e1071", installed.packages()[, 1])) {
  install.packages("e1071", dependencies = TRUE)
}
require("e1071")

sapply(student_dataset[, c( 75, 76, 77, 78, 79, 80, 
                               81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 
                               91, 92, 93, 94, 95, 96, 97, 98, 99)], kurtosis, type = 2)
```

## STEP 13 Measuring the Skewness of each variable

``` r
### STEP 13. Measure the skewness of each variable ----

sapply(student_dataset[, c( 75, 76, 77, 78, 79, 80, 
                               81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 
                               91, 92, 93, 94, 95, 96, 97, 98, 99)], skewness, type = 2)
```

# Measures of Relationship

## STEP 14 Measuring the Covariance between variables

``` r
## STEP 14. Measure the covariance between variables ----
student_data_cov <- cov(student_dataset[, c( 75, 76, 77, 78, 79, 80, 
                               81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 
                               91, 92, 93, 94, 95, 96, 97, 98, 99)])
View(student_data_cov)
```

## STEP 15 Measuring the Correlation between variables

``` r
## STEP 15. Measure the correlation between variables ----
student_data_cor <- cor(student_dataset[, c( 75, 76, 77, 78, 79, 80, 
                                                81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 
                                                91, 92, 93, 94, 95, 96, 97, 98, 99)])
View(student_data_cor)
```

# Statistics

## STEP 16 Performing ANOVA on the students dataset {#you-can-have-another-sub-title-here-if-you-wish}

``` r
##STEP 16. Perform ANOVA on the “student_data” dataset ----

student_data_one_way_anova <- aov (GRADE ~ motivator , data = student_dataset )
summary(student_data_one_way_anova)
```

# Univariate Plots

# STEP 17 Creating Histograms and Plots

We start by creating the Histogram:

``` r
### STEP 17. Create Histograms for Each Numeric Attribute ----
# Identify numeric columns
# Identify numeric columns
numeric_columns <- sapply(student_data, is.numeric)

# Select only the numeric columns
numeric_data <- student_data[, numeric_columns]

# Remove any non-numeric values and convert to numeric
numeric_data <- sapply(numeric_data, function(x) ifelse(is.na(as.numeric(x)), NA, as.numeric(x)))

# Remove columns with all NA values (non-numeric columns)
numeric_data <- numeric_data[, colSums(is.na(numeric_data)) < nrow(numeric_data)]

# Define the number of bins for histograms
num_bins <- 20

# Create histograms for numeric variables
par(mfrow = c(2, 2))  # Adjust the layout based on the number of numeric variables
for (i in 1:ncol(numeric_data)) {
  if (!all(is.na(numeric_data[, i]))) {  # Check if there are no NA values in the column
    hist(numeric_data[, i], main = names(numeric_data)[i], breaks = num_bins)
  }
}


# The name suggesting what the histogram is for
par(mfrow = c(1, 3))
student_regretting <- as.numeric(unlist(student_data[, 4]))
hist(student_regretting, main = names(student_data)[4])

student_read_contet <- as.numeric(unlist(student_data[, 7]))
hist(student_read_contet, main = names(student_data)[7])

student_study_time <- as.numeric(unlist(student_data[, 27]))
hist(student_study_time, main = names(student_data)[27])

student_repeats <- as.numeric(unlist(student_data[, 28]))
hist(student_repeats, main = names(student_data)[28])

student_with_internet <- as.numeric(unlist(student_data[, 36]))
hist(student_with_internet, main = names(student_data)[36])

student_avg_evaluation <- as.numeric(unlist(student_data[, 75]))
hist(student_avg_evaluation, main = names(student_data)[75])

student_avg_learning <- as.numeric(unlist(student_data[, 76]))
hist(student_avg_learning, main = names(student_data)[76])

student_total <- as.numeric(unlist(student_data[, 98]))
hist(student_total, main = names(student_data)[98])
```

# STEP 18 Creating box and Whisker plots

``` r
### STEP 18. Create Box and Whisker Plots for Each Numeric Attribute ----

par(mfrow = c(1, 3))
for (i in 4:6) {
  boxplot(student_data[, i], main = names(student_data)[i])
}
#Avg course evaluation
boxplot(student_data[, 75], main = names(student_data)[75])

par(mfrow = c(1, 7))
for (i in 60:72) {
  boxplot(student_data[, i], main = names(student_data)[i])
}
par(mfrow = c(1, 3))
#learning
boxplot(student_data[, 76], main = names(student_data)[76])
#Totals
par(mfrow = c(1, 2))

boxplot(student_data[, 98], main = names(student_data)[98])
```

# STEP 19 Creating Bar Plots

``` r
### STEP 19. Create Bar Plots for Each Categorical Attribute ----

#Barplot for all categorical data
par(mfrow = c(1, 6))
for (i in 1:6) {for (i in 1:6) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 7:12) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 13:18) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 25:30) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 31:36) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 37:42) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 43:48) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 49:54) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 55:60) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 61:66) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
for (i in 67:72) {
  barplot(table(student_data[, i]), main = names(student_data)[i])
}
```

# STEP 20 Creating a Missingness map

``` r
### STEP 20. Create a Missingness Map to Identify Missing Data ----

if (!is.element("Amelia", installed.packages()[, 1])) {
  install.packages("Amelia", dependencies = TRUE)
}
require("Amelia")

missmap(student_data, col = c("red", "grey"), legend = TRUE)
```

# Multivariate Plots

# STEP 21 Creating a Correlation Plot

``` r
### STEP 21. Create a Correlation Plot ----

if (!is.element("corrplot", installed.packages()[, 1])) {
  install.packages("corrplot", dependencies = TRUE)
}
require("corrplot")
corrplot(cor(student_data[, 4:8]), method = "circle")
corrplot(cor(student_data[, 94:96]), method = "circle")

if (!is.element("ggcorrplot", installed.packages()[, 1])) {
  install.packages("ggcorrplot", dependencies = TRUE)
}
require("ggcorrplot")
#Absentism vs coursework marks
ggcorrplot(cor(student_data[, 95:97]))
#Marks
ggcorrplot(cor(student_data[, 97:99]))
#Avg Course Evaluation
ggcorrplot(cor(student_data[, 75:77]))
```

# STEP 22 Creating a Scatter Plot

``` r
### STEP 22. Create a Scatter Plot ----

ggplot(student_data,
       aes(x = gender, y = study_time, color = class_group)) +
  geom_point() +
  geom_smooth(method = lm)


ggplot(student_data,
       aes(x = YOB, y = study_time, color = class_group)) +
  geom_point() +
  geom_smooth(method = lm)

ggplot(student_data,
       aes(x = gender, y = goal_oriented, color = class_group)) +
  geom_point() +
  geom_smooth(method = lm)
```

# STEP 23 Creating a Multivariate box and Whisker plots by class

``` r
### STEP 23. Create Multivariate Box and Whisker Plots by Class ----
if (!is.element("caret", installed.packages()[, 1])) {
  install.packages("caret", dependencies = TRUE)
}
require("caret")
featurePlot(x = student_data[, 1:3], y = student_data[, 100], plot = "box")
```

**etc.** as per the lab submission requirements. Be neat and communicate in a clear and logical manner.
